loomio_webhooks:
  repo:         https://github.com/loomio/loomio_webhooks

loomio_tags:
  repo:         https://github.com/loomio/loomio_tags

loomio_truncate_comment:
  repo:         https://github.com/loomio/loomio_truncate_comment

loomio_content_preview:
  repo:         https://github.com/loomio/loomio_content_preview

loomio_onboarding:
  repo:         https://github.com/loomio/loomio_onboarding
  branch:       group-form-update
